#!/bin/bash

set -euo pipefail

CMD=${1:-"nocmd"}
PKG=${2:-"nopkg"}

if [[ "${CMD}" == "nocmd" ]]; then
  exit 1
fi

if [[ "${PKG}" == "nopkg" ]]; then
  exit 2
fi

TARGET_PATH_FILENAME="TARGET_PATH"
TARGET_PATH_FILEPATH="${PWD}/pkg/${PKG}/${TARGET_PATH_FILENAME}"

if [ -f "${TARGET_PATH_FILEPATH}" ]; then
  TARGET=$(cat "${TARGET_PATH_FILEPATH}" | envsubst '${HOME}')
else
  TARGET="${HOME}/"
fi

case $CMD in
"install")
  stow -vvv \
    --dir "${PWD}/pkg" \
    --ignore "${TARGET_PATH_FILENAME}" \
    --target "${TARGET}" "${PKG}"
  ;;
*)
  stow -vvv --delete \
    --dir "${PWD}/pkg" \
    --ignore "${TARGET_PATH_FILENAME}" \
    --target "${TARGET}" "${PKG}"
  ;;
esac
