#!/bin/bash

set -euo pipefail

CMD=${1:-"nocmd"}
PKG=${2:-"nopkg"}

if [[ "${CMD}" == "nocmd" ]]; then
  CMD=$(gum choose install delete)
fi

if [[ "${PKG}" == "nopkg" ]]; then
  PKG=$(gum choose $(find pkg -maxdepth 1 -type d | tail -n+2))
  PKG=$(cut -d'/' -f2 <<<"$PKG")
fi

TARGET_PATH_FILENAME="TARGET_PATH"
TARGET_PATH_FILEPATH="${PWD}/pkg/${PKG}/${TARGET_PATH_FILENAME}"

if [ -f "${TARGET_PATH_FILEPATH}" ]; then
  TARGET=$(cat "${TARGET_PATH_FILEPATH}" | envsubst '${HOME}')
else
  TARGET="${HOME}/"
fi

echo $CMD $PKG
gum confirm || exit $?

case $CMD in
"install")
  stow -vvv \
    --dir "${PWD}/pkg" \
    --ignore "${TARGET_PATH_FILENAME}" \
    --target "${TARGET}" "${PKG}"
  ;;
*)
  stow -vvv --delete \
    --dir "${PWD}/pkg" \
    --ignore "${TARGET_PATH_FILENAME}" \
    --target "${TARGET}" "${PKG}"
  ;;
esac
