#!/usr/bin/env bash

brew install \
  amethyst \
  thaw \
  font-hack-nerd-font \
  ghostty \
  gnupg \
  kitty \
  orbstack \
  pinentry \
  pinentry-mac \
  stats \
  syncthing \
  syncthing-app \
  tailscale \
  vim \
  vlc &&
  exit 0
