# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "cryptd" "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8b12caf4-0ea9-4332-831a-07ccb4049c95";
      fsType = "btrfs";
      options = [
        "discard"
      ];
    };

  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/ab5643e0-bdc0-47cc-8e1e-eab8823817b5";
      allowDiscards = true;
      fallbackToPassword = true;
    };
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D883-E775";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.system76.enableAll = true;
  services.power-profiles-daemon.enable = false;

  # MODPROBE_INTEGRATED
  # https://github.com/pop-os/system76-power/blob/master/src/graphics.rs#L55
  boot.extraModprobeConfig = ''
    blacklist i2c_nvidia_gpu
    blacklist nouveau
    blacklist nvidia
    blacklist nvidia-drm
    blacklist nvidia-modeset
    alias i2c_nvidia_gpu off
    alias nouveau off
    alias nvidia off
    alias nvidia-drm off
    alias nvidia-modeset off
  '';

  # Ensure NVIDIA GPU is powered off by default on boot
  systemd.services."nvidia-gpu-poweroff" = let
    power-pkg = config.boot.kernelPackages.system76-power;
  in {
    after = [ "system76-power.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      ${power-pkg}/bin/system76-power graphics power off
    '';
  };

  hardware.graphics = {
    enable = true;
    # enable32bit = true;
  };
}
